# Generated by Django 5.0.7 on 2024-07-20 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.ano')),
            ],
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('enunciado', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_questoes/')),
                ('alternativa_a', models.CharField(max_length=500)),
                ('alternativa_b', models.CharField(max_length=500)),
                ('alternativa_c', models.CharField(max_length=500)),
                ('alternativa_d', models.CharField(max_length=500)),
                ('alternativa_e', models.CharField(max_length=500)),
                ('alternativa_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.ano')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.assunto')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.materia')),
            ],
            options={
                'unique_together': {('numero', 'ano')},
            },
        ),
    ]
