# Generated by Django 5.0.7 on 2024-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='assunto',
        ),
        migrations.AddField(
            model_name='questao',
            name='assuntos',
            field=models.ManyToManyField(to='questoes.assunto'),
        ),
    ]
